import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, Check, Clipboard, FileText, KeyRound, LayoutDashboard, RefreshCw, Save, Settings2, Sparkles, Trash2 } from 'lucide-react'
import { analyzeTemplate, downloadReport, searchReports } from './services/reportService'
import './styles.css'

const initialSources = ['정부·공공기관', '연구·학술', '뉴스', '기업', '국제기구']
const reportTypes = [{ value: '보고용 1장 페이퍼', description: '핵심만 빠르게 공유하는 의사결정용 1페이지 보고서', badge: '빠른 보고' }, { value: '현황-문제점-대응방향', description: '상황을 진단하고 실행 과제까지 정리하는 분석 보고서', badge: '분석형' }]
const SESSION_KEYS = { openai: 'reportly.openai.apiKey', gemini: 'reportly.gemini.apiKey' }
const emptyDraft = { title: '생성 결과가 이곳에 표시됩니다', summary: '입력한 키워드와 조건을 바탕으로 핵심 이슈, 현황, 대응 방향을 정리합니다.', sections: [['핵심 요약', '관련 자료를 종합하면, 해당 이슈는 정책·산업·시민 생활에 걸쳐 점진적으로 영향 범위를 넓히고 있습니다. 주요 변화와 이해관계자의 반응을 중심으로 후속 모니터링이 필요합니다.'], ['주요 현황', '최근 발표 자료와 보도 내용을 기준으로 핵심 사실을 선별합니다. 현재 확인된 흐름, 수치, 주요 주체를 간결하게 정리합니다.'], ['대응 방향', '단기적으로는 사실관계와 영향을 신속히 확인하고, 중장기적으로는 유관 기관과의 공조 및 성과 지표를 설정하는 방향을 제안합니다.']] }
const emptyProviderResult = { ok: null, text: 'API 키를 입력하고 보고서 초안을 생성하면 검색 결과가 표시됩니다.', sources: [], error: null }
const sensitivePatterns = [/\b\d{6}[- ]?\d{7}\b/, /\b01[016789][- ]?\d{3,4}[- ]?\d{4}\b/, /[\w.-]+@[\w.-]+\.[A-Za-z]{2,}/, /\b\d{3,4}[- ]?\d{2,4}[- ]?\d{4,6}\b/]

function readSessionKey(key) { try { return sessionStorage.getItem(key) || '' } catch { return '' } }

function App() {
  const [input, setInput] = useState('')
  const [reportType, setReportType] = useState('보고용 1장 페이퍼')
  const [period, setPeriod] = useState('최근 30일')
  const [sources, setSources] = useState(initialSources)
  const [results, setResults] = useState({ openai: emptyProviderResult, gemini: emptyProviderResult })
  const [references, setReferences] = useState([])
  const [status, setStatus] = useState('idle')
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(false)
  const [openaiKey, setOpenaiKey] = useState(() => readSessionKey(SESSION_KEYS.openai))
  const [geminiKey, setGeminiKey] = useState(() => readSessionKey(SESSION_KEYS.gemini))
  const [keySaveState, setKeySaveState] = useState(() => readSessionKey(SESSION_KEYS.openai) || readSessionKey(SESSION_KEYS.gemini) ? 'saved' : 'empty')
  const [templateFile, setTemplateFile] = useState(null)
  const [template, setTemplate] = useState(null)
  const [templateStatus, setTemplateStatus] = useState('idle')
  const [templatePreviewOpen, setTemplatePreviewOpen] = useState(false)
  const [viewMode, setViewMode] = useState('separate')
  const [downloadStatus, setDownloadStatus] = useState('idle')
  const [providers, setProviders] = useState(['openai', 'gemini'])
  const [maxSources, setMaxSources] = useState(20)

  const toggleSource = (source) => setSources((current) => current.includes(source) ? current.filter((item) => item !== source) : [...current, source])
  const toggleProvider = (provider) => setProviders((current) => current.includes(provider) ? current.filter((item) => item !== provider) : [...current, provider])
  const hasSensitiveData = (value) => sensitivePatterns.some((pattern) => pattern.test(value || ''))
  const handleKeyChange = (provider, value) => { if (provider === 'openai') setOpenaiKey(value); else setGeminiKey(value); setKeySaveState('unsaved'); setError('') }
  const handleSaveSession = () => { try { if (!openaiKey.trim() && !geminiKey.trim()) { sessionStorage.removeItem(SESSION_KEYS.openai); sessionStorage.removeItem(SESSION_KEYS.gemini); setKeySaveState('empty') } else { sessionStorage.setItem(SESSION_KEYS.openai, openaiKey); sessionStorage.setItem(SESSION_KEYS.gemini, geminiKey); setKeySaveState('saved') } setError('') } catch { setError('브라우저 세션 저장을 사용할 수 없습니다.') } }
  const handleClearSession = () => { try { sessionStorage.removeItem(SESSION_KEYS.openai); sessionStorage.removeItem(SESSION_KEYS.gemini) } catch { /* 저장소 접근이 막힌 브라우저에서도 화면 상태는 비웁니다. */ } setOpenaiKey(''); setGeminiKey(''); setKeySaveState('empty'); setError('') }
  const handleTemplateAnalyze = async () => {
    if (!templateFile) return setError('분석할 문서 양식을 먼저 선택해 주세요.')
    setError(''); setTemplateStatus('loading')
    try { const result = await analyzeTemplate(templateFile); if (!result.ok) throw new Error(result.error?.message || '양식 분석에 실패했습니다.'); setTemplate(result); setTemplateStatus('success'); setTemplatePreviewOpen(false) } catch (caught) { setTemplate({ fileName: templateFile.name, error: caught.message }); setTemplateStatus('error') }
  }
  const handleGenerate = async () => {
    if (!input.trim()) return setError('키워드 또는 뉴스 기사 본문을 입력해 주세요.')
    if (!sources.length) return setError('검색 소스를 하나 이상 선택해 주세요.')
    if (!providers.length) return setError('사용할 API를 하나 이상 선택해 주세요.')
    if (hasSensitiveData(input) || hasSensitiveData(template?.markdown)) return setError('개인정보로 보이는 값이 입력되었거나 양식에 포함되어 있습니다. 개인정보를 제거한 뒤 다시 시도해 주세요.')
    setError(''); setStatus('loading'); setCopied(false)
    try { const payload = await searchReports({ input, reportType, period, sources, openaiKey, geminiKey, templatePrompt: template?.templatePrompt, providers, maxSources }); setResults(payload.results); setReferences(payload.sources || []); setViewMode('separate'); setStatus(Object.values(payload.results).some((result) => result.ok) ? 'success' : 'error') } catch { setStatus('error'); setError('검색 요청 중 문제가 발생했습니다. 서버가 실행 중인지 확인해 주세요.') }
  }
  const handleReset = () => { setInput(''); setResults({ openai: emptyProviderResult, gemini: emptyProviderResult }); setReferences([]); setStatus('idle'); setError(''); setCopied(false) }
  const handleCopy = async (provider) => { const result = results[provider]; const text = [result.text, ...references.map((source, index) => `[${index + 1}] ${source.title} ${source.url}`)].join('\n\n'); await navigator.clipboard.writeText(text); setCopied(provider); setTimeout(() => setCopied(false), 1800) }
  const combinedText = [results.openai.ok ? `## OpenAI Web Search\n\n${results.openai.text}` : '', results.gemini.ok ? `## Gemini Google Search\n\n${results.gemini.text}` : ''].filter(Boolean).join('\n\n')
  const requiredSections = reportType === '보고용 1장 페이퍼' ? ['핵심 요약', '현황', '대응방향'] : ['현황', '문제점', '대응방향', '효과성']
  const qualityChecks = [{ label: '핵심 요약 포함', pass: /핵심 요약|요약/i.test(combinedText) }, { label: `${requiredSections.join('·')} 포함`, pass: requiredSections.every((word) => combinedText.includes(word)) }, { label: '근거 인용 포함', pass: references.length > 0 && /\[\d+\]/.test(combinedText) }, { label: '참고할 수 있는 충분한 내용', pass: combinedText.length >= 300 }]
  const templateMatches = (template?.outline || []).map((item) => { const key = item.replace(/^\s*[\d.\-가-힣)]+\s*/, '').slice(0, 30); return { item, pass: key.length > 1 && combinedText.includes(key) } })
  const handleDownload = async (format) => { if (!combinedText) return setError('먼저 성공한 검색 결과를 생성해 주세요.'); setDownloadStatus(format); try { await downloadReport({ format, markdown: combinedText, title: input.trim().slice(0, 40) || 'reportly-report' }) } catch (caught) { setError(caught.message) } finally { setDownloadStatus('idle') } }
  const renderProviderResult = (provider, label) => { const result = results[provider]; return <article className="provider-result"><div className="provider-heading"><div><span className="provider-dot" />{label}</div>{result.ok === true && <button className="copy-button" onClick={() => handleCopy(provider)}>{copied === provider ? <Check size={14} /> : <Clipboard size={14} />}{copied === provider ? '복사됨' : '결과 복사'}</button>}</div>{result.ok === false ? <div className="provider-error"><strong>{result.error?.code === 'NO_API_KEY' ? 'API 키가 없습니다' : '검색에 실패했습니다'}</strong><p>{result.error?.message}</p></div> : <><div className={`report-text ${result.ok === null ? 'placeholder' : ''}`}>{result.text}</div>{result.ok === true && result.sources?.length > 0 && <div className="provider-sources"><strong>검색 출처 {result.sources.length}개</strong>{result.sources.map((source, index) => <a href={source.url} target="_blank" rel="noreferrer" key={`${source.url}-${index}`}>[{source.number}] {source.title}</a>)}</div>}</>}</article> }

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={17} /></div><span>Reportly</span></div><nav><a className="active"><LayoutDashboard size={17} />새 보고서</a><a><FileText size={17} />내 보고서</a></nav><div className="sidebar-bottom"><a><Settings2 size={17} />설정</a><div className="user"><div className="avatar">김</div><div><strong>김정책</strong><small>정책기획팀</small></div><ArrowUpRight size={14} /></div></div></aside>
    <main className="main-content"><header className="topbar"><div><p className="eyebrow">WORKSPACE / NEW REPORT</p><h1>새 보고서 만들기</h1></div><button className="icon-button" aria-label="입력·결과 리셋" onClick={handleReset}><RefreshCw size={18} /></button></header>
      <section className="panel api-panel"><div className="api-heading"><div className="api-title"><KeyRound size={17} /><div><h2>API 연결 설정</h2><p>키는 이 브라우저 탭의 세션에만 보관됩니다.</p></div></div><span className={`key-status ${keySaveState}`}>{keySaveState === 'saved' ? '세션에 저장됨' : keySaveState === 'unsaved' ? '저장되지 않은 변경' : '키 미설정'}</span></div><div className="api-fields"><div className="api-field"><label className="field-label" htmlFor="openai-key">OpenAI API 키</label><input id="openai-key" className="key-input" type="password" value={openaiKey} onChange={(event) => handleKeyChange('openai', event.target.value)} placeholder="sk-..." autoComplete="off" /></div><div className="api-field"><label className="field-label" htmlFor="gemini-key">Gemini API 키</label><input id="gemini-key" className="key-input" type="password" value={geminiKey} onChange={(event) => handleKeyChange('gemini', event.target.value)} placeholder="AIza..." autoComplete="off" /></div></div><div className="provider-options"><div><span className="field-label">사용할 검색 API</span><div className="provider-checks"><label className="check-item"><input type="checkbox" checked={providers.includes('openai')} onChange={() => toggleProvider('openai')} /><span className="checkmark">✓</span>OpenAI Web Search</label><label className="check-item"><input type="checkbox" checked={providers.includes('gemini')} onChange={() => toggleProvider('gemini')} /><span className="checkmark">✓</span>Gemini Google Search</label></div></div><label className="source-limit"><span className="field-label">최대 출처 수</span><select value={maxSources} onChange={(event) => setMaxSources(Number(event.target.value))}><option value="5">5개</option><option value="10">10개</option><option value="15">15개</option><option value="20">20개</option></select></label></div><p className="session-note">세션 비우기를 누르거나 브라우저 탭을 닫으면 저장된 API 키가 삭제됩니다. 서버 로그와 보고서 결과에는 API 키가 표시되지 않습니다.</p><div className="api-actions"><button className="secondary-button" onClick={handleReset}><RefreshCw size={14} />입력·결과 리셋</button><button className="secondary-button primary-outline" onClick={handleSaveSession}><Save size={14} />세션 저장</button><button className="secondary-button danger-outline" onClick={handleClearSession}><Trash2 size={14} />세션 비우기</button></div></section>
      <section className="panel template-panel"><div className="template-heading"><div className="api-title"><FileText size={17} /><div><h2>보고서 양식 분석</h2><p>HWP·HWPX·DOCX·PDF·XLS·XLSX 형식의 기존 양식을 분석해 생성 프롬프트에 반영합니다.</p></div></div><span className={`key-status ${templateStatus === 'success' ? 'saved' : templateStatus === 'error' ? 'unsaved' : 'empty'}`}>{templateStatus === 'success' ? '분석 완료' : templateStatus === 'error' ? '분석 실패' : '선택 사항'}</span></div><div className="template-upload-row"><input id="template-file" type="file" accept=".hwp,.hwpx,.docx,.pdf,.xlsx,.xls" onChange={(event) => { setTemplateFile(event.target.files?.[0] || null); setTemplate(null); setTemplateStatus('idle'); setError('') }} /><label htmlFor="template-file" className="file-picker"><FileText size={15} />{templateFile ? templateFile.name : '문서 양식 선택'}</label><button className="secondary-button primary-outline" onClick={handleTemplateAnalyze} disabled={templateStatus === 'loading'}>{templateStatus === 'loading' ? <><span className="spinner" />분석 중...</> : '양식 분석'}</button></div>{templateStatus === 'success' && <><p className="template-success">{template.fileName} · {template.fileType} · 제목과 항목 순서를 추출했습니다.</p><button className="preview-toggle" onClick={() => setTemplatePreviewOpen((open) => !open)}>{templatePreviewOpen ? '분석 결과 접기' : '분석 결과 미리보기'}</button>{templatePreviewOpen && <div className="template-preview"><strong>추출된 항목</strong><div className="template-outline">{template.outline?.length ? template.outline.map((item, index) => <span key={`${item}-${index}`}>{index + 1}. {item}</span>) : '구조화된 항목을 찾지 못했습니다.'}</div><strong>Markdown 원문</strong><pre>{template.markdown}</pre></div>}</>}{templateStatus === 'error' && <p className="form-error template-error" role="alert">{template.fileName}: {template.error}</p>}</section>
      <div className="workspace-grid"><section className="panel input-panel"><div className="panel-heading"><div><span className="step">01</span><h2>자료와 조건 설정</h2></div><span className="required">필수 입력</span></div>
        <label className="field-label" htmlFor="source-input">키워드 또는 뉴스 기사 본문 <span>*</span></label><textarea id="source-input" maxLength={10000} value={input} onChange={(event) => { setInput(event.target.value); if (error) setError('') }} placeholder="예: 생성형 AI의 공공부문 도입 현황과 주요 쟁점\n\n기사 본문을 직접 붙여넣어도 좋아요." /><div className="char-count">{input.length.toLocaleString()} / 10,000자</div>{hasSensitiveData(input) && <p className="privacy-warning">개인정보로 보이는 값이 감지되었습니다. 외부 API로 전송하기 전에 삭제해 주세요.</p>}
        <div className="field-group"><label className="field-label">보고서 유형</label><div className="option-stack">{reportTypes.map((item) => <label className={`radio-card ${reportType === item.value ? 'selected' : ''}`} key={item.value}><input type="radio" name="report-type" checked={reportType === item.value} onChange={() => setReportType(item.value)} /><span className="radio-dot" /><span className="radio-copy"><strong>{item.value}</strong><small>{item.description}</small></span><em>{item.badge}</em></label>)}</div></div>
        <div className="field-group"><label className="field-label">검색 기간</label><div className="pill-row">{['최근 7일', '최근 30일', '최근 1년', '전체 기간'].map((item) => <label className={`pill ${period === item ? 'selected' : ''}`} key={item}><input type="radio" name="period" checked={period === item} onChange={() => setPeriod(item)} />{item}</label>)}</div></div>
        <div className="field-group"><label className="field-label">검색 소스 <span>*</span></label><div className="checkbox-grid">{initialSources.map((item) => <label className="check-item" key={item}><input type="checkbox" checked={sources.includes(item)} onChange={() => toggleSource(item)} /><span className="checkmark">✓</span>{item}</label>)}</div></div>
        {error && <p className="form-error" role="alert">{error}</p>}<button className="generate-button" disabled={status === 'loading'} onClick={handleGenerate}>{status === 'loading' ? <><span className="spinner" />초안 생성 중...</> : <><Sparkles size={18} />보고서 초안 생성하기 <span>⌘ ↵</span></>}</button><p className="privacy-note">입력한 내용은 보고서 생성을 위해서만 사용됩니다.</p>
      </section><section className={`panel result-panel ${status === 'success' ? 'has-result' : ''}`}><div className="result-top"><div><span className="step">02</span><h2>생성 결과</h2></div>{status !== 'idle' && status !== 'loading' && <span className={`status-badge ${status === 'error' ? 'failed' : ''}`}><span />{status === 'success' ? '검색 완료' : '모든 검색 실패'}</span>}</div>{status === 'success' && <div className="result-toolbar"><div className="view-switch"><button className={viewMode === 'separate' ? 'selected' : ''} onClick={() => setViewMode('separate')}>기관별 결과</button><button className={viewMode === 'combined' ? 'selected' : ''} onClick={() => setViewMode('combined')}>통합 보기</button></div><div className="download-actions"><button className="secondary-button" onClick={() => handleDownload('docx')} disabled={downloadStatus !== 'idle'}>{downloadStatus === 'docx' ? 'DOCX 생성 중...' : 'DOCX 다운로드'}</button><button className="secondary-button" onClick={() => handleDownload('hwpx')} disabled={downloadStatus !== 'idle'}>{downloadStatus === 'hwpx' ? 'HWPX 생성 중...' : 'HWPX 다운로드'}</button></div></div>}{viewMode === 'combined' && status === 'success' ? <article className="provider-result combined-result"><div className="provider-heading"><div><span className="provider-dot" />OpenAI·Gemini 통합 결과</div><button className="copy-button" onClick={() => navigator.clipboard.writeText(combinedText)}>결과 복사</button></div><div className="report-text">{combinedText}</div></article> : <div className="provider-results">{renderProviderResult('openai', 'OpenAI Web Search')}{renderProviderResult('gemini', 'Gemini Google Search')}</div>}{references.length > 0 && <div className="references"><h3>참고 출처</h3>{references.map((source, index) => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>[{index + 1}] {source.title} <span>{source.url}</span></a>)}</div>}{status === 'success' && <><div className="review-panel"><h3>생성 품질 점검</h3>{qualityChecks.map((check) => <div className="review-row" key={check.label}><span className={check.pass ? 'review-pass' : 'review-warn'}>{check.pass ? '✓' : '!'}</span>{check.label}<strong>{check.pass ? '확인' : '검토 필요'}</strong></div>)}</div>{templateMatches.length > 0 && <div className="review-panel"><h3>양식 항목 매칭</h3>{templateMatches.map((match, index) => <div className="review-row" key={`${match.item}-${index}`}><span className={match.pass ? 'review-pass' : 'review-warn'}>{match.pass ? '✓' : '!'}</span>{match.item}<strong>{match.pass ? '적용 완료' : '내용 부족'}</strong></div>)}</div>}</>}</section></div><footer>© 2026 Reportly <span>·</span> 정책과 데이터를 더 빠르게 연결합니다.</footer></main>
  </div>
}

createRoot(document.getElementById('root')).render(<App />)
